language: node_js
node_js:
 - "stable"
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq libbsd-dev
 - sudo apt-get install -qq g++-4.8
